@startuml
class AggiungiDipendenteFragment << (F,#FF7700) Fragment >> {
    -aggiungiDipendenteViewModel: AggiungiDipendenteViewModel
    -fragmentView: View
    -aggiungiDipendenteBinding: FragmentAggiungiDipendenteBinding

    +onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle): View
    +onResume(): void
    +impostaSpinner(): void
    +osservaSeTornareIndietro(): void
    +osservaMessaggioErrore(): void
}
@enduml

